Added doom and cantina band
danilofuchs/ForceTouchPlayer pull request #4
Opened 2021-02-12 13:29 UTC by Zaprit

Because you know, why not™

2021-02-12 21:26 UTC, danilofuchs requested changes
Wow, such nice songs!
_Why not™_ should be the slogan here.

Doom song is playing awesomely!

I'm afraid my Macbook could not handle the higher pitched notes from Doom, and Cantina Band became a big mess 😄 .

I'll improve some things in the player as Doom requires tempo of 300 and the slider goes to 200 max.

Oh, and you should add these songs to the Readme file

2021-02-12 21:26 UTC, danilofuchs commented on ForceTouchPlayer/Songs/Doom.swift
> +    rawNotes: [part1, part2, part3].flatMap { $0 }
I played around a bit and reducing the padding timing from the default `0.25` to `0.1` better represented this song's tempo
```suggestion
let doomE1M1 = Song(
    name: "Doom E1M1",
    defaultTempo: 300.0,
    padding: Note(frequency: 0, value: 0.15),
    rawNotes: [part1, part2, part3].flatMap { $0 }
```

2021-02-13 10:51 UTC, Zaprit commented
There we go, I have added your changes and updated readme

2021-02-19 23:04 UTC, danilofuchs approved these changes

2021-02-19 23:04 UTC, merged